version: '3.7'

services:
  searchapp:
    container_name: text2image
    image: text2image:latest
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant
      - QDRANT_PORT=6333

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./backend/.data/qdrant_storage:/qdrant/storage